---
# tasks file for ansible-tomcat

- include: tomcat_install.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
  tags: [installation]

#- include: tomcat_rollback.yml
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
#  tags: [rollback]

- include: tomcat_testing.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
  tags: [testing]
